### PR TITLE
[Thesis] Replacing TravelTimes with RoadModelSnapshot

### PR DESCRIPTION
**Pull request by VincentVanGestel**
This pull request contains the full refactor from the TravelTimes paradigm to a snapshot design. The road model itself will calculate routes (instead of an external object) using a configurable heuristic. The default values all match the original design of RinSim, allowing for easy adoption.

Possible issues:
- I haven't found an elegant way to prevent code duplication with the snapshot. Both the snapshot as well as the road model implement 2 methods (getPathTo and getDistanceOfPath), the implementations are almost identical.
- For now, for simplicity with the solvers, the heuristic can also calculate travel times (this is not exactly clean as I feel it isn't the responsibility of this heuristic), the benefit is ease of use.

---
This change is [Reviewable](https://reviewable.io/reviews/rinde/rinsim/37)

### CODE REVIEW

**Comment by rinde** [comment]
I've discussed in the models how you can avoid the code duplication. About the second issue I'm not sure yet, wouldn't it be possible to put a similar method as static in some utility class?

---

Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/GraphRoadModelImpl.java, line 399 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5pIWIyVpJjHCWvuhi:-Kd5pIWIyVpJjHCWvuhj:b8m3o47) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/GraphRoadModelImpl.java#L399)):*
> ```Java
>   }
> 
>   @Override
> ```

try to avoid code duplication by forwarding these calls to the snapshot

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneModelSnapshot.java, line 39 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5i754kjTKZCzoqlvv:-Kd5i757B4cbTjEajQCy:bnulbj5) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneModelSnapshot.java#L39)):*
> ```Java
>  *
>  */
> final class PlaneModelSnapshot extends AbstractModelSnapshot {
> ```

rename to PlaneRoadModelSnapshot, use AutoValue, remove abstract super class

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneModelSnapshot.java, line 52 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5k6tlTuRWt85pCSRN:-Kd5k6tlTuRWt85pCSRO:b-z0yjx3) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneModelSnapshot.java#L52)):*
> ```Java
> 
>   @Override
>   public HeuristicPath getPathTo(Point from, Point to, Unit<Duration> timeUnit,
> ```

code duplication is not necessary here, since the plane properties of the PlaneRoadModel and the PlaneRoadModelSnapshot are both immutable, this class can be simplified to just forward calls to the PlaneRoadModel. It therefore requires just one field.

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java, line 99 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5kZhYkCf80b4EQAAK:-Kd5kZhYkCf80b4EQAAL:b-x6uqw6) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java#L99)):*
> ```Java
>     maxSpeed = unitConversion.toInSpeed(b.getMaxSpeed());
>     snapshot = new PlaneModelSnapshot(min, max, getDistanceUnit());
>     fakeGraph = new FakeGraph<>();
> ```

rename to PlaneGraph

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java, line 203 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5lL3PWA25K62XuA_t:-Kd5lL3PWA25K62XuA_u:b8ke002) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java#L203)):*
> ```Java
>       Measure<Double, Velocity> speed, Graphs.Heuristic heuristic) {
>     return new HeuristicPath(
>       Graphs.shortestPath(fakeGraph, from, to, heuristic),
> ```

avoid overhead by just creating a list with from and to. I don't think that given this graph, there is any way the heuristic could ever come up with a different path, right?

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java, line 210 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5m6PCEN07z3lgwr-2:-Kd5m6PDGLQmLylF6Obr:bk8wohj) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java#L210)):*
> ```Java
> 
>   @Override
>   public Measure<Double, Length> getDistanceOfPath(Iterable<Point> path) {
> ```

use Graphs.pathLength(..)

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/RoadModel.java, line 358 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5pam4hRZbfwuZ4zGP:-Kd5pam4hRZbfwuZ4zGQ:b-rad7a1) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/RoadModel.java#L358)):*
> ```Java
> 
>   /**
>    * Finds the optimal path with a given {@link Heuristic} between the points
> ```

Finds a path that is optimal according to the given {@link Heuristic}..

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/RoadModelSnapshot.java, line 59 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5glod_EK7NJ0vtkJF:-Kd5glod_EK7NJ0vtkJG:bpkbkq1) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/RoadModelSnapshot.java#L59)):*
> ```Java
>    * @return The length of the given path in the distance unit of the
>    *         {@link RoadModel}.
>    */
> ```

add @throws IAE in case a path with less than TWO points is supplied, make sure to also check this condition in every implementing class

---

*[geom/src/main/java/com/github/rinde/rinsim/geom/HeuristicPath.java, line 28 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5dvgHiKjGPlUX3Ap7:-Kd5dvgI8LiQFLzhUHLw:b3b2tn0) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/geom/src/main/java/com/github/rinde/rinsim/geom/HeuristicPath.java#L28)):*
> ```Java
>  * @author Vincent Van Gestel
>  */
> public final class HeuristicPath {
> ```

use AutoValue for value classes, see TimeWindow for an example

---

*[geom/src/main/java/com/github/rinde/rinsim/geom/HeuristicPath.java, line 39 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5e-vt4WLVJmo6q1Fx:-Kd5e-vt4WLVJmo6q1Fy:b-9l37sg) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/geom/src/main/java/com/github/rinde/rinsim/geom/HeuristicPath.java#L39)):*
> ```Java
>   public final double value;
>   /**
>    * The perceived travel time of the path by the heuristic.
> ```

Change comment into: "Travel time that it takes to traverse the path as calculated by the heuristic."

---

*[pdptw/src/main/java/com/github/rinde/rinsim/pdptw/common/PDPRoadModel.java, line 315 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5ou6-1rXzWIt5p01Z:-Kd5ou60pQ6HDO_2Mn_Y:b-z8u79h) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/pdptw/src/main/java/com/github/rinde/rinsim/pdptw/common/PDPRoadModel.java#L315)):*
> ```Java
> 
>   @Override
>   public RoadModelSnapshot getSnapshot() {
> ```

is this needed? Shouldn't this already happen in ForwardingRoadModel?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rinde/rinsim/37#-:-Kd5pwNGKNenXvrHOQ88:bwtwzkf)*

**Comment by VincentVanGestel** [comment]
Calculating Travel Times and finding the optimal path is tightly linked. If the path was found using theoretical speeds, the travel time shouldn't be calculated using actual current speeds. But the user of the heuristic doesn't know what implementation it is using. Polymorphism helped to prevent additional configuration or potential conflicts (like described previously), so it is very useful in the Heuristic interface... but also a little bit out of place. Maybe renaming it to strategy instead of heuristic would help?

---

Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/GraphRoadModelImpl.java, line 399 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5pIWIyVpJjHCWvuhi:-Kd6SmGRb7q1TuBUUkMN:b-896fix) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/GraphRoadModelImpl.java#L399)):*
<details><summary><i>Previously, rinde (Rinde van Lon) wrote…</i></summary><blockquote>

try to avoid code duplication by forwarding these calls to the snapshot
</blockquote></details>

Done.

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneModelSnapshot.java, line 39 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5i754kjTKZCzoqlvv:-Kd6V_JJMcq7EjV698uy:b-896fix) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneModelSnapshot.java#L39)):*
<details><summary><i>Previously, rinde (Rinde van Lon) wrote…</i></summary><blockquote>

rename to PlaneRoadModelSnapshot, use AutoValue, remove abstract super class
</blockquote></details>

Done.

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneModelSnapshot.java, line 52 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5k6tlTuRWt85pCSRN:-Kd6Vat6nPvSFAXiabNB:b-p330ei) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneModelSnapshot.java#L52)):*
<details><summary><i>Previously, rinde (Rinde van Lon) wrote…</i></summary><blockquote>

code duplication is not necessary here, since the plane properties of the PlaneRoadModel and the PlaneRoadModelSnapshot are both immutable, this class can be simplified to just forward calls to the PlaneRoadModel. It therefore requires just one field.
</blockquote></details>

Switched.

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java, line 99 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5kZhYkCf80b4EQAAK:-Kd6VhwTbjCeZ1LIx8l-:bt1b19p) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java#L99)):*
<details><summary><i>Previously, rinde (Rinde van Lon) wrote…</i></summary><blockquote>

rename to PlaneGraph
</blockquote></details>

Renamed.

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java, line 203 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5lL3PWA25K62XuA_t:-Kd6Y5ixQ5Hew2vquLaa:b-wfvekx) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java#L203)):*
<details><summary><i>Previously, rinde (Rinde van Lon) wrote…</i></summary><blockquote>

avoid overhead by just creating a list with from and to. I don't think that given this graph, there is any way the heuristic could ever come up with a different path, right?
</blockquote></details>

True, isn't this somehow limiting to the heuristic? Say you want a heuristic that looks for the shortest path that includes the bounds of the plane/graph. That wouldn't be possible with the current setup. Not sure if that would be useful, but it is still a limitation.

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java, line 210 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5m6PCEN07z3lgwr-2:-Kd6Zl3bPsg5Y4KSkJfV:b-7zrk6s) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java#L210)):*
<details><summary><i>Previously, rinde (Rinde van Lon) wrote…</i></summary><blockquote>

use Graphs.pathLength(..)
</blockquote></details>

Used.

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/RoadModel.java, line 358 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5pam4hRZbfwuZ4zGP:-Kd6ZxB7paRMef_ijeI_:b-a2ujfl) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/RoadModel.java#L358)):*
<details><summary><i>Previously, rinde (Rinde van Lon) wrote…</i></summary><blockquote>

Finds a path that is optimal according to the given {@link Heuristic}..
</blockquote></details>

Changed.

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/RoadModelSnapshot.java, line 59 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5glod_EK7NJ0vtkJF:-Kd6afS_Eib44_6v38kY:bu01jjj) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/RoadModelSnapshot.java#L59)):*
<details><summary><i>Previously, rinde (Rinde van Lon) wrote…</i></summary><blockquote>

add @throws IAE in case a path with less than TWO points is supplied, make sure to also check this condition in every implementing class
</blockquote></details>

Added and Checked. I'd however argue that it is possible to check the distance of a path with only ONE point, as that ``path'' would simply be of length zero.

---

*[geom/src/main/java/com/github/rinde/rinsim/geom/HeuristicPath.java, line 28 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5dvgHiKjGPlUX3Ap7:-Kd6cUwM9Vqzafk6Hne6:b-896fix) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/geom/src/main/java/com/github/rinde/rinsim/geom/HeuristicPath.java#L28)):*
<details><summary><i>Previously, rinde (Rinde van Lon) wrote…</i></summary><blockquote>

use AutoValue for value classes, see TimeWindow for an example
</blockquote></details>

Done.

---

*[geom/src/main/java/com/github/rinde/rinsim/geom/HeuristicPath.java, line 39 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5e-vt4WLVJmo6q1Fx:-Kd6e4RGiiKbO90CzT_L:b-a2ujfl) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/geom/src/main/java/com/github/rinde/rinsim/geom/HeuristicPath.java#L39)):*
<details><summary><i>Previously, rinde (Rinde van Lon) wrote…</i></summary><blockquote>

Change comment into: "Travel time that it takes to traverse the path as calculated by the heuristic."
</blockquote></details>

Changed.

---

*[pdptw/src/main/java/com/github/rinde/rinsim/pdptw/common/PDPRoadModel.java, line 315 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5ou6-1rXzWIt5p01Z:-Kd6eEm8Vu5JapkFIYGB:bss4a2b) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/pdptw/src/main/java/com/github/rinde/rinsim/pdptw/common/PDPRoadModel.java#L315)):*
<details><summary><i>Previously, rinde (Rinde van Lon) wrote…</i></summary><blockquote>

is this needed? Shouldn't this already happen in ForwardingRoadModel?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rinde/rinsim/37#-:-Kd6eIubQc8H0Kak7JEW:beqrmcr)*

**Comment by rinde** [comment]
some minor issues remain

---

Reviewed 1 of 28 files at r1, 14 of 14 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/DynamicGraphRoadModelImpl.java, line 221 at r2](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd6myskBRDBQEbEyT2z:-Kd6myslkC5L5LOLcm_7:b98ogfg) ([raw file](https://github.com/rinde/rinsim/blob/a1cd714e293d41bd5098335d8670c2dfa1966a9c/core/src/main/java/com/github/rinde/rinsim/core/model/road/DynamicGraphRoadModelImpl.java#L221)):*
> ```Java
>    * change to the graph occurs.
>    */
>   protected void updateSnapshot() {
> ```

why isn't this done lazily anymore? that could potentially save a lot of time right?

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/GraphRoadModelSnapshot.java, line 47 at r2](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd6jyDzR2Ih8d4x0Z9z:-Kd6jyE0_OIJ2NVyRIUu:b-39tz0p) ([raw file](https://github.com/rinde/rinsim/blob/a1cd714e293d41bd5098335d8670c2dfa1966a9c/core/src/main/java/com/github/rinde/rinsim/core/model/road/GraphRoadModelSnapshot.java#L47)):*
> ```Java
>     implements RoadModelSnapshot {
> 
>   GraphRoadModelSnapshot() {}
> ```

the convention with AutoValue classes is to create a static factory method create(..) that calls the AutoValue_Constructor, please change the classes accordingly. The idea is to minimise exposure to AutoValue internals from other places (check the AutoValue docs for mor info).

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java, line 99 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5kZhYkCf80b4EQAAK:-Kd6nNoEJU3gqMSwdpdR:b2ni9ah) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java#L99)):*
<details><summary><i>Previously, VincentVanGestel (Vincent Van Gestel) wrote…</i></summary><blockquote>

Renamed.
</blockquote></details>

ok

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java, line 203 at r1](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd5lL3PWA25K62XuA_t:-Kd6nWzLmaMVyMSykqmr:b32wtd) ([raw file](https://github.com/rinde/rinsim/blob/14a0fc0d93e8964445466415c4561d9cec23fa68/core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModel.java#L203)):*
<details><summary><i>Previously, VincentVanGestel (Vincent Van Gestel) wrote…</i></summary><blockquote>

True, isn't this somehow limiting to the heuristic? Say you want a heuristic that looks for the shortest path that includes the bounds of the plane/graph. That wouldn't be possible with the current setup. Not sure if that would be useful, but it is still a limitation.
</blockquote></details>

ok

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModelSnapshot.java, line 34 at r2](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd6l9j-PRm67ODltHBl:-Kd6l9j-PRm67ODltHBm:botcq68) ([raw file](https://github.com/rinde/rinsim/blob/a1cd714e293d41bd5098335d8670c2dfa1966a9c/core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModelSnapshot.java#L34)):*
> ```Java
>  */
> @AutoValue
> abstract class PlaneRoadModelSnapshot
> ```

add create(..) method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rinde/rinsim/37#-:-Kd6oSnEeayHyrxVhawn:bsbtjcw)*

**Comment by VincentVanGestel** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/DynamicGraphRoadModelImpl.java, line 221 at r2](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd6myskBRDBQEbEyT2z:-Kd6rXe9X3mY4PdoRG5W:b-ypaj2h) ([raw file](https://github.com/rinde/rinsim/blob/a1cd714e293d41bd5098335d8670c2dfa1966a9c/core/src/main/java/com/github/rinde/rinsim/core/model/road/DynamicGraphRoadModelImpl.java#L221)):*
<details><summary><i>Previously, rinde (Rinde van Lon) wrote…</i></summary><blockquote>

why isn't this done lazily anymore? that could potentially save a lot of time right?
</blockquote></details>

I had changed it since GraphRoadModelImpl passes getPathTo to the GraphRoadModelSnapshot, but I guess that can also be done lazily, I'll revert that change.

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/GraphRoadModelSnapshot.java, line 47 at r2](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd6jyDzR2Ih8d4x0Z9z:-Kd6uC1poOoBikbErvu5:b-25kk4q) ([raw file](https://github.com/rinde/rinsim/blob/a1cd714e293d41bd5098335d8670c2dfa1966a9c/core/src/main/java/com/github/rinde/rinsim/core/model/road/GraphRoadModelSnapshot.java#L47)):*
<details><summary><i>Previously, rinde (Rinde van Lon) wrote…</i></summary><blockquote>

the convention with AutoValue classes is to create a static factory method create(..) that calls the AutoValue_Constructor, please change the classes accordingly. The idea is to minimise exposure to AutoValue internals from other places (check the AutoValue docs for mor info).
</blockquote></details>

Added missing creates.

---

*[core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModelSnapshot.java, line 34 at r2](https://reviewable.io:443/reviews/rinde/rinsim/37#-Kd6l9j-PRm67ODltHBl:-Kd6uagUrpVjkZOQ5w1Z:b-896fix) ([raw file](https://github.com/rinde/rinsim/blob/a1cd714e293d41bd5098335d8670c2dfa1966a9c/core/src/main/java/com/github/rinde/rinsim/core/model/road/PlaneRoadModelSnapshot.java#L34)):*
<details><summary><i>Previously, rinde (Rinde van Lon) wrote…</i></summary><blockquote>

add create(..) method
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rinde/rinsim/37)*

**Comment by rinde** [comment]
Reviewed 1 of 14 files at r2, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rinde/rinsim/37)*

**Pull request merged**
